### ISSUE TITLE
What is the difference between Julia PATH and GAMS PATH? 

### ISSUE THREAD

**Issue by linyuantiaohe** [chkwon/PATHSolver.jl#69] opened 2022-10-07 11:33 UTC
Hi, I'm trying to transfer GAMS code to Julia, but I met some problem in kind of "large" scale model.

For example, a simple multi-region tech planning model. If there is only 1 region, both PATHSolver.jl and GAMS PATH can obtain the same solution. When repeating the 1 region to 10 regions  for example, GAMS can still find solution while Julia cannot.

The Julia code could give termination_status such as  "SLOW_PROGRESS::TerminationStatusCode = 19" or "ITERATION_LIMIT::TerminationStatusCode = 11"

I put the codes here, thank you very much for your help!

## GAMS code (change the set  r to /1*n/ to change the amount of regions )
```
set r /1*10/,
t /1*3/;

parameter
fixcost(t)/
1 4
2 1
3 12/,
variablecost(t)/
1 0.03
2 0.05
3 0.001/,
efficient(t)/
1 40
2 20
3 80/,
maxtech(t);

maxtech(t)=100;

parameter demand(r);
demand(r)= 10000;

positive variables
newtech(t,r),
sell(t,r),
buy(t,r),
price(t,r);

newtech.up(t,r)=maxtech(t);

negative variable
a_outputmax(t,r);

free variable
b_demandmeet(r);

equations
outputmax(t,r),
kkt_newtech(t,r),
kkt_sell(t,r),
demandmeet(r),
kkt_buy(t,r),
mc(t,r);

outputmax(t,r)..   sell(t,r)-newtech(t,r)*efficient(t) =l= 0;
kkt_newtech(t,r)..  fixcost(t)+a_outputmax(t,r)*efficient(t) =e=0;
kkt_sell(t,r)..  (variablecost(t)-price(t,r))-a_outputmax(t,r) =e=0;
demandmeet(r)..  sum(t,buy(t,r))-demand(r) =e= 0;
kkt_buy(t,r)..  price(t,r)-b_demandmeet(r)=e=0;
mc(t,r)..       sell(t,r)-buy(t,r)=e=0;


model m /outputmax.a_outputmax,kkt_newtech.newtech,kkt_sell.sell,demandmeet.b_demandmeet,kkt_buy.buy,mc.price/;
solve m using mcp;
```

## Julia code (change the regions to 1:n to change the amount of regions)
```
using PATHSolver, JuMP
PATHSolver.c_api_License_SetString("2830898829&Courtesy&&&USR&45321&5_1_2021&1000&PATH&GEN&31_12_2025&0_0_0&6000&0_0")

regions=1:5
tech=1:3

fixcost=[4,1,12]
variablecost=[0.03,0.05,0.001]
efficient=[40,20,80]
maxtech=[100 for t in tech]
demand=[10000 for i in regions]

m=Model(PATHSolver.Optimizer)
@variable(m, 0<= newtech[t in tech, r in regions] <= maxtech[t])
@variable(m, sell[t in tech,r in regions] >= 0)
@variable(m, buy[t in tech,r in regions] >= 0)
@variable(m, price[t in tech,r in regions])

@variable(m, a_outputmax[t in tech,r in regions] <= 0)
@variable(m, b_demandmeet[r in regions])

@constraint(m, outputmax[t in tech,r in regions], sell[t,r]-newtech[t,r]*efficient[t] ⟂ a_outputmax[t,r])

@constraint(m, kkt_newtech[t in tech,r in regions],fixcost[t]+a_outputmax[t,r]*efficient[t] ⟂ newtech[t,r])
@constraint(m, kkt_sell[t in tech,r in regions],(variablecost[t]-price[t,r])-a_outputmax[t,r] ⟂ sell[t,r])

@constraint(m,demandmeet[r in regions],sum(buy[t,r] for t in tech)- demand[r] ⟂ b_demandmeet[r])

@constraint(m, kkt_buy[t in tech,r in regions],price[t,r]-b_demandmeet[r] ⟂ buy[t,r])

@constraint(m, mc[t in tech,r in regions],sell[t,r]-buy[t,r] ⟂ price[t,r])

set_optimizer_attribute(m, "minor iteration limit", "10000000")
set_optimizer_attribute(m, "major iteration limit", "10000000")
optimize!(m)
termination_status(m)
```

**Comment by odow** [comment] 2022-10-08 22:19
I think this is a slight mis-match between your `=e=` definition of the equations, and the `positive` definition of the associated variables? What happens in GAMS if you make all relations `=N=`? 

If I remove the explicit positivity in JuMP, then I get the solution:
```julia
using JuMP
import PATHSolver

function main()
    tech, regions = 1:3, 1:10
    fixcost, variablecost = [4, 1, 12], [0.03, 0.05, 0.001]
    efficient = [40, 20, 80]
    maxtech = [100 for _ in tech]
    demand = [10_000 for _ in regions]
    model = Model(PATHSolver.Optimizer)
    set_silent(model)
    @variables(model, begin
        newtech[t=tech, regions] <= maxtech[t]
        sell[tech, regions]
        buy[tech, regions]
        price[tech, regions]
        a_outputmax[tech, regions] <= 0
        b_demandmeet[regions]
    end)
    @constraints(model, begin
        [t=tech, r=regions], sell[t,r] - newtech[t,r] * efficient[t] ⟂ a_outputmax[t,r]
        [t=tech, r=regions], fixcost[t] + a_outputmax[t,r] * efficient[t] ⟂ newtech[t,r]
        [t=tech, r=regions], variablecost[t] - price[t,r] - a_outputmax[t,r] ⟂ sell[t,r]
        [r=regions], sum(buy[:, r]) - demand[r] ⟂ b_demandmeet[r]
        [t=tech, r=regions], price[t,r] - b_demandmeet[r] ⟂ buy[t,r]
        [t=tech, r=regions], sell[t,r] - buy[t,r] ⟂ price[t,r]
    end)
    optimize!(model)
    @assert termination_status(model) == LOCALLY_SOLVED
    @assert all(value.(newtech) .>= 0)
    @assert all(value.(sell) .>= 0)
    @assert all(value.(buy) .>= 0)
    @assert all(value.(price) .>= 0)
    return model
end
```

**Comment by linyuantiaohe** [comment] 2022-10-09 08:58
You are right. Remove the variables' positivity  in JuMP can get the same solution as replacing " =e=" by "=N=" in GAMS. 

Thank you very much!

**Comment by linyuantiaohe** [comment] 2022-10-09 09:12
I'm not sure what is the reason. When I add the amounts of regions to 30, the model returns "SLOW_PROGRESS::TerminationStatusCode = 19", but when I further add regions to 40, the model can be solved again.

Do I need to set any options in "set_optimizer_attribute"?

**Comment by linyuantiaohe** [comment] 2022-10-09 09:24
> I'm not sure what is the reason. When I add the amounts of regions to 30, the model returns "SLOW_PROGRESS::TerminationStatusCode = 19", but when I further add regions to 40, the model can be solved again.
> 
> Do I need to set any options in "set_optimizer_attribute"?

The reason should be the M1 macbook. I borrowed a windows computer and didn't meet this problem.

**Comment by odow** [comment] 2022-10-09 20:26
> The reason should be the M1 macbook. I borrowed a windows computer and didn't meet this problem.

Yes. This is potentially just numerical stability issues that will vary from machine to machine. Does GAMS have the same problem? There might be some settings you can change, but I wouldn't know which ones.

**Comment by linyuantiaohe** [comment] 2022-10-11 06:27
GAMS don't have this problem. Thank you.

**Comment by odow** [comment] 2022-10-11 19:36
I guess it's a setting issue then, or a difference in how Michael compiled PATH for macOS. But it doesn't seem like a bug in PATHSolver.jl.

What version of PATH does GAMS use?

You could also try using a different factorization method: https://github.com/chkwon/PATHSolver.jl#factorization-methods

**Comment by odow** [comment] 2022-11-10 20:01
Closing because I don't know what else there is to do here. It's not a bug in PATHSolver.jl. GAMS might do additional pre-processing steps, but that's not something we can dig into.

**Closed as completed by odow** 2022-11-10 20:01 UTC
